//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckinCheckout
    {
        public System.Guid ID { get; set; }
        public string PhoneNumberID { get; set; }
        public Nullable<System.DateTimeOffset> Checkin { get; set; }
        public Nullable<System.DateTimeOffset> Checkout { get; set; }
        public string Purpose { get; set; }
        public string Device { get; set; }
    }
}
